[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
futures = "0.3"
tokio-tungstenite = "0.24.0"
mongodb = "3.1.0"

yapping_core = { path = "../yapping_core" }

[profile.release]
lto = true
codgen-units = 1
panic = "abort"